Updated search for players ships to pass indices to data.ships so it can be retrieved
Example error:

Traceback (most recent call last):
File "./player_dump.py", line 45, in <module>
starsystem = data.ships[ship].starsystem
TypeError: list indices must be integers or slices, not edict

Changed to:
starsystem = data.ships[data.ships.index(ship)].starsystem

This returns the indices correctly where the ship exists in the
dictionary.

Replaced as appropriate in code. Tested against Python 3.5